### ISSUE TITLE
About using SBCB on the SegFormer

### ISSUE THREAD

**Issue by SAWRJJ** [haruishi43/boundary_boost_mmseg#1]
Thank you for the excellent model you provided. Recently, I want to apply the SBCB module you proposed on the segformer, but I encountered a problem with the channel. Can you provide the config for applying SBCB on the segformer? Thank you for your help.

**Comment by haruishi43** [comment]
@SAWRJJ Of course! I added configs under `configs/segformer`. I also added the `mod-mit` config that uses a larger feature size in the backbone that I found improves mIoU scores. If you're planning to use the larger mit5, I found that SBCB doesn't have as much effect... Hope this helps!

**Comment by SAWRJJ** [comment]
> @SAWRJJ Of course! I added configs under `configs/segformer`. I also added the `mod-mit` config that uses a larger feature size in the backbone that I found improves mIoU scores. If you're planning to use the larger mit5, I found that SBCB doesn't have as much effect... Hope this helps!

Thank you very much.
